# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew and is not meant to be edited directly.
# For details, see: https://docs.brew.sh/Formula-Cookbook

class Schoolcode < Formula
  desc "Automated developer tool deployment for macOS Guest accounts"
  homepage "https://github.com/luka-loehr/SchoolCode"
  url "https://github.com/luka-loehr/SchoolCode/archive/refs/tags/v3.0.1.tar.gz"
  sha256 "" # Will be calculated after creating release - check GitHub Actions workflow output
  license "Apache-2.0"
  head "https://github.com/luka-loehr/SchoolCode.git", branch: "main"

  depends_on "bash"

  def install
    # Install main script as executable
    bin.install "schoolcode.sh" => "schoolcode"
    
    # Install all scripts to libexec/scripts
    libexec.install Dir["scripts"]
    
    # Install version.txt to libexec
    libexec.install "version.txt" if File.exist?("version.txt")
    
    # Make all scripts executable
    Dir["#{libexec}/**/*.sh"].each { |f| chmod 0755, f }
    
    # Make main script executable
    chmod 0755, bin/"schoolcode"
  end

  def post_install
    # Run SchoolCode installation script
    # This will perform full installation: compatibility check, system repair, tool installation, guest setup
    ohai "Running SchoolCode installation..."
    ohai "This requires sudo privileges and will set up Guest account tools."
    
    # Run with explicit error handling
    unless system "sudo", "#{bin}/schoolcode", "--install"
      opoo "SchoolCode installation encountered an issue."
      opoo "You can manually complete installation by running:"
      opoo "  sudo schoolcode --install"
    end
  end

  def uninstall
    # Run SchoolCode uninstall script before removing package
    if File.exist?("#{bin}/schoolcode")
      system "sudo", "#{bin}/schoolcode", "--uninstall"
    end
  end

  test do
    # Test that the command exists and shows help
    system "#{bin}/schoolcode", "--help"
  end
end

